#cloud-config

%{ if length(authorized_key_bootstrap) > 0 ~}
ssh_authorized_keys:
  - ${authorized_key_bootstrap}
%{ endif ~}

write_files:
  - path: /config.ign
    permissions: 0600
    content: |
      ${ignition_config}

  - path: /takeover.sh
    permissions: 0700
    content: |
      ${takeover_script}

runcmd:
  %{ if length(pre_takeover) > 0 ~}
  - ${pre_takeover}
  %{ endif ~}
  - /takeover.sh
  %{ if length(post_takeover) > 0 ~}
  - ${post_takeover}
  %{ endif ~}
